apiVersion: v1
kind: Pod # Настройка образа, запуск контэйнера, контэйнер контэйнеров, группировка контэйнеров для одной цели
metadata:
  name: client-pod
  labels:
    component: web # По этому лэйблу связываем по с другими сущностями. Например можно написать tier: front
spec:
  containers:
    - name: client # Имя контэйнера
      image: stephengrider/multi-client # Образ откуда его качать
      ports:
        - containerPort: 3000 # Порт, который не ведет никуда. Он используется в Nginx что бы прослушивать его. Как только он откроется, значит контэйнер поднят