apiVersion: v1
kind: Service # Настройка сети
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050       # Порт для общения между сервисами внутри kubernetes
      targetPort: 3000 # Порт самого контэйнера в поде
      nodePort: 31515  # Порт для доступа из вне. Если не указать, назначится случайный порт
  selector:
    component: web # По этому ключу сервис понимет с чем связывать его. Например под, с которыйм надо связать, может иметь такой ключ tier: front

# ClusterIP    - Доступ только внутри кластера. Никто из вне не сможет достучаться до пода
# NodePort     - Открывет доступ к сервису извне (советуют использовать только для разработки)
# LoadBalancer - Балансирует нагрузку между одни типом подов. Устарел
# Ingress      - Балансирует нагрузку между несколькими подами разного типа