apiVersion: apps/v1
kind: Deployment # Для создания набора подов
metadata:
  name: client-deployment
spec:
  replicas: 1 # Количество реплик для объекта template
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000